apiVersion: v1
kind: Service
metadata:
  name: python-starter
  labels: 
    app: python-starter
spec:
  type: ClusterIP
  selector:
    app: python-starter
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-starter
  labels: 
    app: python-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-starter
  template:
    metadata:
      labels:
        app: python-starter
    spec:
      containers:
      - name: python-starter
        image: gcr.io/k8s-skaffold/python-starter
        ports:
        - containerPort: 5000