apiVersion: skaffold/v1beta5
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dirty_{{.SKAFFOLD_TAG_SUFFIX}}"
  artifacts:
  - image: gcr.io/k8s-skaffold/lotr-quotes
    context: ./lotr-quotes/
    sync:
      '**/*.js': /usr/src/app
  - image: gcr.io/k8s-skaffold/python-starter
    context: ./python-starter/
    sync:
      '**/*.py': /usr/src/app
  - image: gcr.io/k8s-skaffold/message-writer
    context: ./message-writer/
    sync:
      '**/*.py': /usr/src/app
  - image: gcr.io/k8s-skaffold/food-message-receiver
    context: ./food-message-receiver/
  - image: gcr.io/k8s-skaffold/food-job-worker
    context: ./food-job-worker/


deploy:
  kubectl:
    manifests:
    - ./lotr-quotes/k8s/*
    - ./python-starter/k8s/*
    - ./message-writer/k8s/*
    - ./food-message-receiver/k8s/*
    - ./infrastructure/**/k8s/*

profiles:
- name: only-message
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:dirty_{{.SKAFFOLD_TAG_SUFFIX}}"
    artifacts:
    - image: gcr.io/k8s-skaffold/message-writer
      context: ./message-writer/
      sync:
        '**/*.py': /usr/src/app
    - image: gcr.io/k8s-skaffold/food-message-receiver
      context: ./food-message-receiver/
      sync:
        '**/*.py': /usr/src/app
    - image: gcr.io/k8s-skaffold/food-job-worker
      context: ./food-job-worker/


- name: only-lotr
  build: 
    artifacts:
    - image: gcr.io/k8s-skaffold/lotr-quotes
      context: ./lotr-quotes/
      sync:
        '**/*.js': /usr/src/app
  deploy:
    kubectl:
      manifests:
      - ./lotr-quotes/k8s/*

- name: only-starter
  build: 
    artifacts:
    - image: gcr.io/k8s-skaffold/python-starter
      context: ./python-starter/
      sync:
        '**/*.py': /usr/src/app

  deploy:
    kubectl:
      manifests:
      - ./python-starter/k8s/*

