apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/lotr-quotes
    context: ./lotr-quotes
    # sync:
    #   '**/*.js': .

deploy:
  kubectl:
    manifests:
    - ./lotr-quotes/k8s/*